### ISSUE TITLE
[Crash] Stackflow Overload crash

### ISSUE THREAD

**Issue by Lanse505** [hilburn/StevesAddons#37]
https://gist.github.com/anonymous/45a926cee082767036d3

---- Minecraft Crash Report ----
// I just don't know what went wrong :(
 
Time: 4/10/15 5:20 PM
Description: Ticking block entity
 
java.lang.StackOverflowError: Ticking block entity
        at net.minecraft.world.World.func_147438_o(World.java:2536)
        at stevesaddons.tileentities.TileEntityRFNode.getTileEntityOnSide(TileEntityRFNode.java:123)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:106)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)
        at stevesaddons.tileentities.TileEntityRFNode.receiveEnergy(TileEntityRFNode.java:109)

-------------------------------------------------------------------------------------------------------------------------------

This happens on build 0.10.0 so we're abit behind but still wanted to report this

This happens when you try putting RF via a RFNode into a RFTools Machine

**Comment by hilburn** [comment]
Ok - thanks for this - I'll look into it

**Comment by Lanse505** [comment]
Cheers :P

**Comment by hilburn** [comment]
Also - you should be able to move RF directly into them just by putting them next to a cable - the RF nodes are just designed to facilitate moving power from awkward TEs

**Comment by marduvGitHub** [comment]
My server did also crash http://pastebin.com/XU0QCTpv :-(
Last build I did use was 0.10.2

**Comment by hilburn** [comment]
@marduvGitHub - that is a completely different issue - please open one

**Comment by hilburn** [comment]
Should be fixed in latest release as RFNodes were massively reworked

**Comment by Lanse505** [comment]
Thanks Guys :) keep up the great work
