### ISSUE TITLE
Manager Crash Log

### ISSUE THREAD

**Issue by Tacos4brekky** [hilburn/StevesAddons#70]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[03/6/2015 17:24:16 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[03/6/2015 17:24:16 PM] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel FactoryManager
[03/6/2015 17:24:16 PM] java.lang.IndexOutOfBoundsException: Index: 240, Size: 232
[03/6/2015 17:24:16 PM]         at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at vswe.stevesfactory.components.FlowComponent.readNetworkComponent(FlowComponent.java:1039) ~[FlowComponent.class:?]
[03/6/2015 17:24:16 PM]         at vswe.stevesfactory.blocks.TileEntityManager.readUpdatedData(TileEntityManager.java:612) ~[TileEntityManager.class:?]
[03/6/2015 17:24:16 PM]         at vswe.stevesfactory.network.PacketEventHandler.onClientPacket(PacketEventHandler.java:30) ~[PacketEventHandler.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.eventhandler.ASMEventHandler_1541_PacketEventHandler_onClientPacket_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[03/6/2015 17:24:16 PM]         at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[03/6/2015 17:24:16 PM]         at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[03/6/2015 17:24:16 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[03/6/2015 17:24:16 PM]         at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[03/6/2015 17:24:16 PM]         at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[03/6/2015 17:24:16 PM] [Server thread/INFO] [Mekanism]: VoiceServer: Shutting down server...
[03/6/2015 17:24:16 PM] [Server thread/INFO] [ProjectE]: Saved transmutation and alchemical bag data.
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension 0
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -1
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension 1
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -100
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension 42
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -37
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -38
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -39
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -42
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -19
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension -112
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension 6
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension 3
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Unloading dimension 2
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Applying holder lookups
[03/6/2015 17:24:19 PM] [Server thread/WARN] [FML]: Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?
[03/6/2015 17:24:19 PM] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[03/6/2015 17:24:19 PM] [Server thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[03/6/2015 17:24:19 PM] [Server thread/INFO] [FML]: Holder lookups applied
[03/6/2015 17:24:22 PM] [17:24:22] [pool-6-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data saved to **USERSDIR**\Instances\RR3World\saves\World X\enderio\dimensionalTransceiver.json
[03/6/2015 17:24:22 PM] [Server thread/INFO] [ProjectE]: Completed server-stop actions.
[03/6/2015 17:24:22 PM] [Server thread/INFO] [STDOUT]: [mcjty.rftools.RFTools:serverStopped:196]: ###### RFTools.serverStopped
[03/6/2015 17:24:22 PM] [Server thread/INFO] [mcjty.rftools.RFTools]: Cleaning up RFTools dimensions
[03/6/2015 17:24:22 PM] [Client thread/INFO] [Mekanism]: VoiceServer: Stopping client connection...
[03/6/2015 17:24:22 PM] [Client thread/INFO] [Mekanism]: Finished loading Cardboard Box blacklist (loaded 0 entries)
[03/6/2015 17:24:22 PM] [Client thread/INFO] [Mekanism]: Reloaded config.
[03/6/2015 17:24:22 PM] [Client thread/INFO] [STDOUT]: [com.thevoxelbox.voxelmap.t:d:-1]: reset dimension info 0.5

**Comment by hilburn** [comment]
Yeah.. your manager seems to be borked
I cannot for the life of me see how the TF broke it though

**Comment by Tacos4brekky** [comment]
It may not have even been TF, just listed that last major event that occurred before it broke.  

And okay, I'll try doing that.  Is there any way to best get in contact with him?

**Comment by hilburn** [comment]
He has a minefraft forum post - but I don't know
